use std::str::FromStr;
use ::value::Value;

#[LALR] grammar;

pub Bool: Value = {
  "true" => Value::new_bool(true),
  "false" => Value::new_bool(false),
};

pub Char: Value = {
    <c:r"#\\\S"> => Value::new_char(c.chars().take(2).next().unwrap()),
};

pub Integer: Value = {
    <i:r"[0-9]+"> => Value::new_integer(i64::from_str(i).unwrap()),
    "-" <i:r"[0-9]+"> => Value::new_integer(-i64::from_str(i).unwrap()),
};
